-- Seed 28 players with base prices (admin will adjust prices in UI)
-- Tentative players marked with status 'tentative'
insert into players (name, base_price, status) values
  ('Ankush', 50, 'confirmed'),
  ('Arpit', 50, 'confirmed'),
  ('Sanjeev Sir', 50, 'confirmed'),
  ('Zizou', 50, 'confirmed'),
  ('Mayank Chaturvedi', 50, 'confirmed'),
  ('Yavart', 50, 'confirmed'),
  ('Pritam', 50, 'confirmed'),
  ('Jayant', 50, 'confirmed'),
  ('Mukul', 50, 'confirmed'),
  ('Shailendra', 50, 'confirmed'),
  ('Akshaj', 50, 'confirmed'),
  ('Chiru', 50, 'confirmed'),
  ('Bishu', 50, 'confirmed'),
  ('Rohit', 50, 'confirmed'),
  ('Prajjwal', 50, 'confirmed'),
  ('Anush', 50, 'confirmed'),
  ('Rakshit', 50, 'confirmed'),
  ('Harsh', 50, 'confirmed'),
  ('Ankur', 50, 'tentative'),
  ('Puneet', 50, 'confirmed'),
  ('Penny', 50, 'confirmed'),
  ('Rohan', 50, 'confirmed'),
  ('Yojit', 50, 'confirmed'),
  ('Vansh', 50, 'tentative'),
  ('Archit', 50, 'confirmed'),
  ('SK', 50, 'confirmed'),
  ('Gaurav', 50, 'tentative'),
  ('Eesh', 50, 'tentative');
